[package]
name = "actix-ai-ms"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.7.0"
rust-bert = "0.22.0"
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.117"
